- docker-compose.dev.yml
Remember, CORS has to be enabled manually:
http://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksCORsEnableSPARQLURLs
This will be replaced by an embedded yasgui later.
> Added yasgui for development

- config/dispatcher/dispatcher.ex
- docker-compose.yml
Since this endpoint mostly gets the same queries over and over it makes sense to provide a caching layer. The varnish cache used has a default caching period of 30min. 
a slight delay in updates is appreciated in improved performance by caching.
We'll need to investigate if the default max document size of 2MB is sufficient for our query responses
> use varnish to cache queries

- .changeset/hungry-cooks-camp.md
- docker-compose.yml
This PR updates the frontend to 1.4.1 (contains a fix to the URL shown in the footer)
> Update frontend to 1.4.1

- .changeset/light-wasps-change.md
- config/resources/domain.json
The recent update to `mu-cl-resources` 1.23.0 includes some changes in the handling of undefined resource models.
This PR ensures that relationships pointing to undefined models are removed.
Specifically, the following relationships have been removed:
- road-marking-concept
* status
- traffic-light-concept
* status
* categories
- road-sign-concept
* measures
These errors are probably a combination of mistakes in plurality/singularity; and copying model definitions from the MOW application.
https://github.com/lblod/app-gelinkt-notuleren/pull/178
- run `mu project doc` and observe that the generation of `json:api` docs executes without errors
Some of the relationships that are removed in this PR (mainly the `status` relationships) are still present in the models on the frontend, but they do …
> Remove unresolvable relationships from resource models

- .changeset/odd-schools-hang.md
- .changeset/slimy-tables-switch.md
- config/migrations/20240613085754-fix-non-zonal-uri.sparql
- config/migrations/20240613090626-fill-in-missing-zonalities.sparql
This PR fixes two data issues related to the zonality of road-signs/traffic-measures:
- Fill-in of missing zonalities of road-signs and traffic-measures
- Fix a typo in the usage of the non-zonal URI (http://lblod.data.gift/concepts/b651931b-923c-477c-8da9-fc7dd841fdccZ> to 
http://lblod.data.gift/concepts/b651931b-923c-477c-8da9-fc7dd841fdcc)
None
- Start the application
- Ensure (when querying with sparql) there are no missing zonalities and the correct zonality URIs are used
> Fix data issues related to zonality URIs

- .changeset/polite-ways-talk.md
- config/migrations/20240620115606-fill-in-missing-zonalities-workaround.sparql
- config/resources/domain.json
Add hacky workaround to ensure road-marking and traffic-light concepts can be correctly consumed:
- Addition of a migration which adds default zonalities to traffic-light and road-marking concepts
- Add `zonality` relationship to traffic-light and road-marking concepts in JSON-API definitions
> add hacky workaround to ensure road-sign and traffic-light concepts can be correctly consumed

- config/resources/domain.json
`mobiliteit:Pictogram` can be linked to multiple `lblodmow:Codelist`.
Related to GN-4917
linked to https://github.com/lblod/app-mow-registry/pull/79
> Fix skosConcepts inScheme cardinality

- config/authorization/config.ex
- config/dispatcher/dispatcher.ex
- config/migrations/20240730174403-mapping-to-variable.sparql
- config/resources/domain.json
These are the backend changes related to ticket https://binnenland.atlassian.net/browse/GN-4925
In these changes we replaced the mapping resource with the variable resource.
Link to PR:
frontend: https://github.com/lblod/frontend-mow-registry/pull/259
> Replace mappings resource with variable

- config/migrations/20240806110449-remove-definitions.sparql
- config/resources/domain.json
Remove definition attribute from:
- road marking concepts
- traffic light concepts
https://binnenland.atlassian.net/browse/GN-4971
frontend: https://github.com/lblod/frontend-mow-registry/pull/264
> remove definition from backend

- config/migrations/20241002151500-trim-traffic-measure-labels.sparql
We now display the suffix in the frontend where needed.
> [GN-5070] Remove the hardcoded `Traffic measure` suffix from the labels in the DB

- docker-compose.yml
latest version of the ldes-delta-pusher service has many changes that broke our current configuration.
I've fixed the version to 0.4.1 for now (in the override), so that it unblocks external testers / implementers.
> fix ldes delta pusher version

- config/migrations/20241206131500-fix-template-variable.sparql
- The predicate migrations on `ext:Template` in https://github.com/lblod/app-mow-registry/blob/version/2.0.0/config/migrations/20240730174403-mapping-to-variable.sparql#L6-L46 has no effect. 
- Due to a previous template type migration https://github.com/lblod/app-mow-registry/blob/version/2.0.0/config/migrations/20240429115806-migration-to-oslo-template.sparql#L8-L22
The missing migration is now applied on the new `mobiliteit:Template` type.
> Fix Template predicate

- config/migrations/20241206121500-variable-title-to-value.sparql
In previous migration, `ext:variable` were migrated into `dct:title` instead of value. https://github.com/lblod/app-mow-registry/blob/version/2.0.0/config/migrations/20240730174403-mapping-to-variable.sparql#L48-L66
This PR add a migration to migrate `dct:title` into `rdf:value`.
> Migrate variable title to value

- .changeset/chilly-squids-leave.md
- docker-compose.dev.yml
- docker-compose.yml
~~Also remove use of unpinned frontend version as it could cause local testing inconsistencies and isn't the correct way to test new versions locally.~~
Also add a restart configuration for the tombstone service in production.
N/A
N/A
Restart your docker daemon and notice the services don't get automatically started.
N/A
> Prevent restart of services on developer machines

- .changeset/smooth-chicken-happen.md
- config/migrations/20250130151407-drop-annotated-templates.sparql
- config/resources/domain.json
This PR includes support for template previews.
Specifically:
- The `annotated` property of the `template` model has been removed
- A `preview` property has been added to the `template` model
https://github.com/lblod/frontend-mow-registry/pull/315
https://github.com/lblod/fix-annotation-service/pull/17
Include both https://github.com/lblod/frontend-mow-registry/pull/315 and https://github.com/lblod/fix-annotation-service/pull/17 in your stack:
```yml
frontend:
image: !reset null
build: https://github.com/lblod/frontend-mow-registry.git#feat/template-previews
annotater:
image: !reset null
build: https://github.com/lblod/fix-annotation-service.git#feat/template-previews
```
- Start the stack
- Ensure the migration runs correctly
- (Optional) call the `/update-all` endpoint of the …
> feat(templates): introduce support for template previews

- .changeset/curvy-cobras-agree.md
- .changeset/large-feet-double.md
- .changeset/sharp-trees-smash.md
- .changeset/smooth-chicken-happen.md
- config/migrations/20250128130820-variable-value-to-label.sparql
- config/migrations/20250130151407-drop-annotated-templates.sparql
- config/resources/domain.json
- docker-compose.yml
This PR slightly adjust the variable data-model to use the `dct:title` predicate instead of the `rdf:value` predicate to represent the label/title of a variable:
- A migration is included to replace instances of `rdf:value` by `dct:title`
- The `rdf:value` property has been removed from the mu-cl-resources variable data-model
https://github.com/lblod/fix-annotation-service/pull/16
https://github.com/lblod/frontend-mow-registry/pull/314
Include both https://github.com/lblod/fix-annotation-service/pull/16 and https://github.com/lblod/frontend-mow-registry/pull/314 in your stack:
```yml
frontend:
image: !reset null
build: https://github.com/lblod/frontend-mow-registry.git#fix/variable-value-to-label
annotater:
image: !reset null
build: …
```
> variables: replace `rdf:value` by `dct:title`

- .changeset/chatty-mails-visit.md
- .changeset/new-lemons-fix.md
- config/delta/rules.js
- config/migrations/20250205105230-fix-template-value-predicate.sparql
- config/resources/domain.json
- docker-compose.yml
This PR ensures the correct predicate (`rdf:value`) is used to represent the value of `mobiliteit:Template` resources (coming from `prov:value`).
https://github.com/lblod/fix-annotation-service/pull/19
Include https://github.com/lblod/fix-annotation-service/pull/19 in your stack:
```yml
annotater:
image: !reset null
build: https://github.com/lblod/fix-annotation-service.git#fix/template-value
```
- Start the triplestore & migrations. Ensure the migrations ran correctly
- Start the rest of the stack
- Ensure `prov:value` is no longer used in the triplestore
- Ensure the frontend still works correctly
- Ensure the `annotater` service does its job.
> Use correct predicate to represent template value/content

- .changeset/big-socks-itch.md
- config/migrations/20250218133000-fix-roadsign-shapes.sparql
This PR shapes the shapes to how they want them:
- Renames Driehoekig, Achthoekig , Ruitvormig and Wegwijzer met puntvorm to shortened names
- Deletes Klein ruitvormig and converts all the signs with this shape to Ruit
- Renames Groot bord to Rechthoek
- Adds Omgekeerde driehoek 
- Fixes the uri base of tribont shapes to match the rest
GN-5427
None
Run the migration and check the changes are made and they are correct 
None
> Add migration to fix roadsign shapes

- .changeset/cuddly-lies-lick.md
- scripts/init-ldes-data/app.mjs
This PR adds the missing `variables` prefix to to a SPARQL query in the `init-ldes-data` script
- Execute the `init-ldes-data` mu script and ensure it succeeds
> fix: add missing prefix to `init-ldes-data` script

- .changeset/small-jeans-deliver.md
- config/dispatcher/dispatcher.ex
Expose raw-sparql endpoint for the validity dates
GN-2702
None
Notice you can now send sparql queries without cache to /raw-sparql
None
> expose raw-sparql endpoint

- .changeset/sharp-rats-fly.md
- docker-compose.yml
This PR updates and pins the `lblod/ldes-serve-feed-service` to version [0.1.0](https://github.com/lblod/ldes-serve-feed-service/releases/tag/v0.1.0).
> Pin `lblod/ldes-serve-feed-service` to version 0.1.0

- .changeset/silent-garlics-join.md
- config/delta/rules.js
- config/ldes-delta-pusher/healing.ts
- config/migrations/20250324154000-clear-multiple-modified-dates.sparql
- config/modified/config.ts
- docker-compose.yml
Setup autohealing for the ldes stream, for this I had to also add the modified service which is a service that add a dct:modified to the ldes types.
GN-5449
None
Weird one to test, basically you can modify a ldes type, for example a roadsign, go to the ldes ttl file, delete that change, then run the healing (by changing the cronjob pattern in the docker compose) and then check that your change was restored
None
> setup ldes autohealing

- .changeset/late-roses-retire.md
- config/delta/rules.js
GN-5566
The MOW registry makes 15 requests to save a measure. If the total time for all of these requests exceeds one second, the ldes delta pusher may generate invalid data, because it still checks the triplestore to determine which information is currently active. By substantially increasing the grace period, we can find a stable point where the ldes delta pusher  is more likely to produce correct information. 
https://github.com/user-attachments/assets/5ec21435-6f5f-4597-85b7-d4533edf2e6a
> increase grace period to 15sec

- .changeset/hungry-ducks-guess.md
- config/migrations/20250520100918-fix-category-uri-typo.sparql
This PR fixes the 'catergorie' typo in roadsign-category uris using a migration.
- Ensure the migration runs correctly and the roadsign-category uris have been correctly updated
> fix(typo): fix 'catergorie' typo in roadsign-category uris

- .changeset/lemon-dots-tie.md
- config/migrations/20250523105700-change-template-property.sparql
- config/resources/domain.json
A template couldn't be linked to 2 variables, due to the model constraint of the inverse parentConceptOf linked to a mobility measure.
After talking with Niels we decided to separate this 2 properties.
Warning: this affects consuming apps so we should deploy the changes in sync
GN-5596
None
Check that you can add a instruction variable linked with the same template in 2 different measures
None
> Fix template property to differentiate variable and mobility measure

- .changeset/cold-ligers-perform.md
- config/resources/domain.json
This PR moves the `shapes` relationship from the `road-sign-concept` class to the parent `traffic-sign-concept` class. This is needed to also support shapes for road-marking-concepts.
[GN-5546](https://binnenland.atlassian.net/browse/GN-5546?atlOrigin=eyJpIjoiM2I5ZjQwNmY2ZmY3NDkxMWFkZGIwM2ZiYjI0NmFjNzQiLCJwIjoiaiJ9)
https://github.com/lblod/frontend-mow-registry/pull/329
Check-out https://github.com/lblod/frontend-mow-registry/pull/329
> GN-5546: add support for adding shapes to road-marking-concepts

- .changeset/sixty-goats-accept.md
- config/resources/domain.json
Changes the resources API but not the model.
Works with https://github.com/lblod/frontend-mow-registry/pull/337
Needs to run with the new frontend to avoid breaking the traffic measures screen
In the traffic measures screen, the links to related signs/markings/lights work correctly.
I wasn't sure to change the base-url, but figure it shouldn't actually change anything as it's just a URI.
> Rename traffic sign to traffic signal

- .changeset/loud-rivers-speak.md
- docker-compose.yml
This PR introduces an update to the `feature-construct-updates` tag of sparql-parser.
It uses `CONSTRUCT` queries when deleting and inserting data instead of relying on `OPTIONAL` statements.
This will hopefully resolve the issue where deleting road-signs fails, but that issue is quite hard to reproduce. 
It seems to happen on road-signs with a lot of properties/relationships, but even then this is not guaranteed. 
[GN-5637](https://binnenland.atlassian.net/browse/GN-5637?atlOrigin=eyJpIjoiZDY0MGQ3Y2ExYTViNDhiYmIxOWEzZTE0ZDQxOTJkZDciLCJwIjoiaiJ9)
- Start the app
- Ensure editing/adding/removing concepts/codelist/icons still works
**Reproducing the delete-road-sign bug/issue**
- Create a road-sign concept with a lot of properties and relationships + create backup of the DB
- Set-up the …
> Update sparql-parser to `feature-construct-updates` tag

- .changeset/curly-points-impress.md
- config/migrations/20250923124700-fix-height-and-width-shape.sparql
- config/resources/domain.json
Add inverse for traffic sign concept for shapes and variables to support pagination
GN-5692
https://github.com/lblod/frontend-mow-registry/pull/346
Use with the frontend PR https://github.com/lblod/frontend-mow-registry/pull/346
Check that the pagination works on the frontend
None
> add inverse to support pagination in shapes and variables

- .changeset/blue-lobsters-beam.md
- config/dispatcher/dispatcher.ex
- docker-compose.yml
This (draft) PR sets-up the services and dispatcher rules to get ember-metis to work:
- `uri-info` (https://github.com/redpencilio/mu-uri-info-service/): looks up the outgoing and incoming triples for a certain uri/subject
- `resource-labels` (https://github.com/lblod/resource-label-service): looks up the label for a certain uri (rdfs:label or skos:prefLabel)
- `resource-labels-cache`: a cache for the `resource-labels` service
[GN-5726](https://binnenland.atlassian.net/browse/GN-5726?atlOrigin=eyJpIjoiZGQyNGRlOWJmNTk5NGI1YTkzMDM4MWY2NDFiZGFkNjEiLCJwIjoiaiJ9)
https://github.com/lblod/frontend-mow-registry/pull/352
Ensure you are running https://github.com/lblod/frontend-mow-registry/pull/352 as the frontend
Note: we currently don't have URIs with the …
> GN-5726 (part 2): set-up ember-metis
